routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::group(['middleware' => 'api', 'prefix' => 'api/sale'], function () {

    Route::get('/', [
        'uses' => 'ApiSaleController@index',
        'as' => 'api.sale',
    ]);

    Route::get('/total', [
        'uses' => 'ApiSaleController@total',
        'as' => 'api.sale.total',
    ]);

});

Route::resource('attendance', 'AttendanceController');

Route::get('/', [
    'uses' => 'HomeController@index',
    'as' => 'home',
]);

Route::group(['middleware' => 'auth'], function () {

    Route::get('/products', [
        'uses' => 'HomeController@products',
        'as' => 'products',
    ]);

    Route::get('/categories', [
        'uses' => 'HomeController@categories',
        'as' => 'categories',
    ]);

    Route::post('/order-product', [
        'uses' => 'HomeController@order',
        'as' => 'order.product',
    ]);

    Route::post('/logout', [
        'uses' => 'Auth\LoginController@logout',
        'as' => 'logout',
    ]);

});

Route::group(['middleware' => 'guest'], function () {

    Route::get('/login', [
        'uses' => 'Auth\LoginController@loginForm',
        'as' => 'login',
    ]);

    Route::post('/login', [
        'uses' => 'Auth\LoginController@login',
        'as' => 'login',
    ]);

    Route::get('/register', [
        'uses' => 'Auth\RegisterController@registrationForm',
        'as' => 'register',
    ]);

    Route::post('/register', [
        'uses' => 'Auth\RegisterController@register',
        'as' => 'register',
    ]);

});

Route::group(['middleware' => 'auth', 'prefix' => 'stock', 'middleware' => ['role:Admin']], function () {

    Route::get('/logs', [
        'uses' => 'StockController@logs',
        'as' => 'stock.logs',
    ]);

});

Route::group(['middleware' => 'auth', 'prefix' => 'cart', 'middleware' => ['role:Client']], function () {

    Route::patch('/process-order/{order}', [
        'uses' => 'CartController@processOrder',
        'as' => 'cart.process-order',
    ]);

    Route::patch('/detach-product/{product}', [
        'uses' => 'CartController@detachProduct',
        'as' => 'cart.detach-product',
    ]);

});

Route::group(['middleware' => 'auth', 'prefix' => 'order-client', 'middleware' => ['role:Client']], function () {

    Route::patch('/cancel-order/{order}', [
        'uses' => 'OrderClientController@cancelOrder',
        'as' => 'order-client.cancel-order',
    ]);

});

Route::group(['middleware' => 'auth', 'middleware' => ['role:Client']], function () {

    Route::resource('/order-client', 'OrderClientController');

    Route::resource('/cart', 'CartController');

});

Route::group(['middleware' => 'auth', 'middleware' => ['role:Cashier']], function () {

    Route::resource('/payslip', 'PayslipController');

});

Route::group(['middleware' => 'auth', 'middleware' => ['role:Admin|Cashier']], function () {

    Route::get('/dashboard', [
        'uses' => 'DashboardController@index',
        'as' => 'dashboard',
    ]);

});

Route::group(['middleware' => 'auth', 'middleware' => ['role:Admin']], function () {

    Route::resource('stock', 'StockController');

    Route::resource('product', 'ProductController');

    Route::resource('category', 'CategoryController');

    Route::resource('payroll', 'PayrollController');

    Route::resource('user', 'UserController');

    Route::resource('supplier', 'SupplierController');

});

Route::group(['middleware' => 'auth', 'middleware' => ['role:Admin|Cashier']], function () {

    Route::resource('transaction', 'TransactionController');

    Route::resource('order', 'OrderController');

});

Route::group(['middleware' => 'auth', 'prefix' => 'order', 'middleware' => ['role:Admin|Cashier']], function () {

    Route::patch('/cancel-order/{order}', [
        'uses' => 'OrderController@cancelOrder',
        'as' => 'order.cancel-order',
    ]);

    Route::patch('/payment-order/{order}', [
        'uses' => 'OrderController@paymentOrder',
        'as' => 'order.payment-order',
    ]);

    Route::patch('/detach-product/{product}', [
        'uses' => 'OrderController@detachProduct',
        'as' => 'order.detach-product',
    ]);

});

resources/views/partials/admin/_head.blade.php
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>EGA | Panel</title>
<link rel="stylesheet" type="text/css" href="{{ asset('deep-blue-admin/bootstrap/css/bootstrap.min.css') }}" />
<link rel="stylesheet" type="text/css" href="{{ asset('deep-blue-admin/font-awesome/css/font-awesome.min.css') }}" />
<link rel="stylesheet" type="text/css" href="{{ asset('deep-blue-admin/css/local.css') }}" />
<link rel="stylesheet" type="text/css" href="http://www.shieldui.com/shared/components/latest/css/light-bootstrap/all.min.css" />
<link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" />
<style>
    .mgt-b10 {
        margin-bottom: 10px;
    }
    .text-red {
        color: red;
    }
</style>

resources/views/partials/admin/_javascript.blade.php
<script type="text/javascript" src="{{ asset('deep-blue-admin/js/jquery-1.10.2.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('deep-blue-admin/bootstrap/js/bootstrap.min.js') }}"></script>
<script type="text/javascript" src="http://www.shieldui.com/shared/components/latest/js/shieldui-all.min.js"></script>
<script type="text/javascript" src="http://www.prepbootstrap.com/Content/js/gridData.js"></script>
<script type="text/javascript" src="//cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>

resources/views/partials/admin/_nav.blade.php
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="{{ auth()->user()->hasRole('Client') ? route('cart.index') : route('dashboard') }}">EGA Panel</a>
    </div>
    <div class="collapse navbar-collapse navbar-ex1-collapse">
        <ul class="nav navbar-nav side-nav">
            @if(Auth::user())
            @if(auth()->user()->hasRole(['Admin', 'Cashier']))
            <li class="{{Request::is('dashboard') ? 'active' : ''}}">
                <a href="{{route('dashboard')}}"><i class="fa fa-bullseye"></i> Dashboard</a>
            </li>
            @endif
            @if(auth()->user()->hasRole('Admin'))
            <li class="{{Request::is('category', 'category/*') ? 'active' : ''}}">
                <a href="{{route('category.index')}}"><i class="fa fa-tags"></i> Category</a>
            </li>
            <li class="{{Request::is('supplier', 'supplier/*') ? 'active' : ''}}">
                <a href="{{route('supplier.index')}}"><i class="fa fa-users"></i> Supplier</a>
            </li>
            <li class="{{Request::is('product', 'product/*') ? 'active' : ''}}">
                <a href="{{route('product.index')}}"><i class="fa fa-shopping-bag"></i> Product</a>
            </li>
            <li class="{{Request::is('stock', 'stock/*') ? 'active' : ''}}">
                <a href="{{route('stock.index')}}"><i class="fa fa-list-alt"></i> Stock</a>
            </li>
            @endif
            @if(auth()->user()->hasRole(['Admin', 'Cashier']))
            <li class="{{Request::is('order', 'order/*') ? 'active' : ''}}">
                <a href="{{route('order.index')}}"><i class="fa fa-shopping-cart"></i> Order</a>
            </li>
            <li class="{{Request::is('transaction', 'transaction/*') ? 'active' : ''}}">
                <a href="{{route('transaction.index')}}"><i class="fa fa-exchange"></i> Transaction</a>
            </li>
            @endif
            @if(auth()->user()->hasRole('Client'))
            <li class="{{Request::is('cart', '/*') ? 'active' : ''}}">
                <a href="{{route('cart.index')}}"><i class="fa fa-shopping-cart"></i> Cart</a>
            </li>
            <li class="{{Request::is('order-client', 'order-client/*') ? 'active' : ''}}">
                <a href="{{route('order-client.index')}}"><i class="fa fa-shopping-cart"></i> Orders</a>
            </li>
            @endif
            @if(auth()->user()->hasRole('Admin'))
            <li class="{{Request::is('payroll', 'payroll/*') ? 'active' : ''}}">
                <a href="{{route('payroll.index')}}"><i class="fa fa-paypal"></i> Payroll</a>
            </li>
            <li class="{{Request::is('user', 'user/*') ? 'active' : ''}}">
                <a href="{{route('user.index')}}"><i class="fa fa-user"></i> User Management</a>
            </li>
            @endif
            @if(auth()->user()->hasRole('Cashier'))
            <li class="{{Request::is('payslip', 'payslip/*') ? 'active' : ''}}">
                <a href="{{route('payslip.index')}}"><i class="fa fa-user"></i> Payslip</a>
            </li>
            @endif
            @endif
        </ul>
        <ul class="nav navbar-nav navbar-right navbar-user">
            <li class="dropdown user-dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i> {{auth()->user()->first_name}}<b class="caret"></b></a>
                <ul class="dropdown-menu">
                    <li><a onclick="document.getElementById('form-logout').submit()" href="#"><i class="fa fa-power-off"></i> Log Out</a></li>
                </ul>
            </li>
        </ul>
        @if(Auth::user())
        <form id="form-logout" method="POST" action="{{ route('logout') }}">
            {{ csrf_field() }}
        </form>
        @endif
    </div>
</nav>