routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::group(['middleware' => 'api', 'prefix' => 'api/sale'], function () {

    Route::get('/', [
        'uses' => 'ApiSaleController@index',
        'as' => 'api.sale',
    ]);

    Route::get('/total', [
        'uses' => 'ApiSaleController@total',
        'as' => 'api.sale.total',
    ]);

});

Route::resource('attendance', 'AttendanceController');

Route::get('/', [
    'uses' => 'HomeController@index',
    'as' => 'home',
]);

Route::group(['middleware' => 'auth'], function () {

    Route::get('/products', [
        'uses' => 'HomeController@products',
        'as' => 'products',
    ]);

    Route::get('/categories', [
        'uses' => 'HomeController@categories',
        'as' => 'categories',
    ]);

    Route::post('/order-product', [
        'uses' => 'HomeController@order',
        'as' => 'order.product',
    ]);

    Route::post('/logout', [
        'uses' => 'Auth\LoginController@logout',
        'as' => 'logout',
    ]);

});

Route::group(['middleware' => 'guest'], function () {

    Route::get('/login', [
        'uses' => 'Auth\LoginController@loginForm',
        'as' => 'login',
    ]);

    Route::post('/login', [
        'uses' => 'Auth\LoginController@login',
        'as' => 'login',
    ]);

    Route::get('/register', [
        'uses' => 'Auth\RegisterController@registrationForm',
        'as' => 'register',
    ]);

    Route::post('/register', [
        'uses' => 'Auth\RegisterController@register',
        'as' => 'register',
    ]);

});

Route::group(['middleware' => 'auth', 'prefix' => 'stock', 'middleware' => ['role:Admin']], function () {

    Route::get('/logs', [
        'uses' => 'StockController@logs',
        'as' => 'stock.logs',
    ]);

});

Route::group(['middleware' => 'auth', 'prefix' => 'cart', 'middleware' => ['role:Client']], function () {

    Route::patch('/process-order/{order}', [
        'uses' => 'CartController@processOrder',
        'as' => 'cart.process-order',
    ]);

    Route::patch('/detach-product/{product}', [
        'uses' => 'CartController@detachProduct',
        'as' => 'cart.detach-product',
    ]);

});

Route::group(['middleware' => 'auth', 'prefix' => 'order-client', 'middleware' => ['role:Client']], function () {

    Route::patch('/cancel-order/{order}', [
        'uses' => 'OrderClientController@cancelOrder',
        'as' => 'order-client.cancel-order',
    ]);

});

Route::group(['middleware' => 'auth', 'middleware' => ['role:Client']], function () {

    Route::resource('/order-client', 'OrderClientController');

    Route::resource('/cart', 'CartController');

});

Route::group(['middleware' => 'auth', 'middleware' => ['role:Cashier']], function () {

    Route::resource('/payslip', 'PayslipController');

});

Route::group(['middleware' => 'auth', 'middleware' => ['role:Admin|Cashier']], function () {

    Route::get('/dashboard', [
        'uses' => 'DashboardController@index',
        'as' => 'dashboard',
    ]);

});

Route::group(['middleware' => 'auth', 'middleware' => ['role:Admin']], function () {

    Route::resource('stock', 'StockController');

    Route::resource('product', 'ProductController');

    Route::resource('category', 'CategoryController');

    Route::resource('payroll', 'PayrollController');

    Route::resource('user', 'UserController');

    Route::resource('supplier', 'SupplierController');

});

Route::group(['middleware' => 'auth', 'middleware' => ['role:Admin|Cashier']], function () {

    Route::resource('transaction', 'TransactionController');

    Route::resource('order', 'OrderController');

});

Route::group(['middleware' => 'auth', 'prefix' => 'order', 'middleware' => ['role:Admin|Cashier']], function () {

    Route::patch('/cancel-order/{order}', [
        'uses' => 'OrderController@cancelOrder',
        'as' => 'order.cancel-order',
    ]);

    Route::patch('/payment-order/{order}', [
        'uses' => 'OrderController@paymentOrder',
        'as' => 'order.payment-order',
    ]);

    Route::patch('/detach-product/{product}', [
        'uses' => 'OrderController@detachProduct',
        'as' => 'order.detach-product',
    ]);

});

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $fillable = [
        'name',
    ];

    public function products()
    {
        return $this->hasMany('App\Product');
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Http\Requests\CategoryRequest;
use Session;

class CategoryController extends Controller
{
    public function index()
    {
        $categories = Category::all();
        return view('modules.category.index', compact('categories'));
    }

    public function create()
    {
        return view('modules.category.create');
    }

    public function store(CategoryRequest $request)
    {
        $category = new Category;
        $category->fill($request->all())->save();
        Session::flash('flash_message', 'Category has been added!');
        return redirect()->route('category.index');
    }

    public function show($id)
    {
        return;
    }

    public function edit($id)
    {
        $category = Category::find($id);
        return view('modules.category.edit', compact('category'));
    }

    public function update(CategoryRequest $request, $id)
    {
        $category = Category::find($id);
        $category->update($request->all());
        Session::flash('flash_message', 'Category has been updated!');
        return redirect()->route('category.index');
    }

    public function destroy($id)
    {
        $category = Category::find($id);
        $category->delete();
        Session::flash('flash_message', 'Category has been deleted!');
        return redirect()->back();
    }
}

resources/views/modules/category/create.blade.php
@extends('layouts.admin')
@section('content')
<div class="row">
    <div class="col-lg-12">
        @include('partials.helper._message')
        <h1>Category <small>Category create</small></h1>
    </div>
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title"><i class="fa fa-shopping-bag"></i> Category create</h3>
            </div>
            <div class="panel-body">
                <form action="{{route('category.store')}}" method="POST">
                    {{ csrf_field() }}
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="form-group">
                                <label>Category</label>
                                <input required name="name" value="{{old('name')}}" class="form-control" placeholder="Category">
                            </div>
                            <div class="form-group">
                                <button type="submit" class="btn btn-success form-control">Save</button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/modules/category/edit.blade.php
@extends('layouts.admin')
@section('content')
<div class="row">
    <div class="col-lg-12">
        @include('partials.helper._message')
        <h1>Category <small>Category edit</small></h1>
    </div>
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title"><i class="fa fa-shopping-bag"></i> Category edit</h3>
            </div>
            <div class="panel-body">
                <form action="{{route('category.update', $category->id)}}" method="POST">
                    {{ method_field('PATCH') }}
                    {{ csrf_field() }}
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="form-group">
                                <label>Category</label>
                                <input required name="name" value="{{$category->name}}" class="form-control" placeholder="Category">
                            </div>
                            <div class="form-group">
                                <button type="submit" class="btn btn-success form-control">Update</button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/modules/category/index.blade.php
@extends('layouts.admin')
@section('content')
<div class="row">
    <div class="col-lg-12">
        @include('partials.helper._message')
        <h1>Category <small>Category list</small></h1>
        <a href="{{route('category.create')}}" class="btn btn-info mgt-b10">Create Category</a>
    </div>
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title"><i class="fa fa-shopping-bag"></i> Category list</h3>
            </div>
            <div class="panel-body">
                <div class="table-responsive">
                    <table class="table table-striped" id="datatable">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Name</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($categories as $category)
                            <tr>
                                <td>{{$category->id}}</td>
                                <td>{{$category->name}}</td>
                                <td>
                                    <a href="{{route('category.edit', $category->id)}}" class="btn btn-info"><i class="fa fa-pencil-square-o"></i></a>
                                    <button type="submit" form="category-delete-{{$category->id}}" class="btn btn-danger"><i class="fa fa-trash-o"></i></button>
                                    <form onsubmit="return confirm('Do you want to delete this data?');" id="category-delete-{{$category->id}}" action="{{route('category.destroy', $category->id)}}" method="POST">
                                        {{ method_field('DELETE') }}
                                        {{ csrf_field() }}
                                    </form>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
@section('scripts')
<script>
    $(document).ready(function(){
        $('#datatable').DataTable();
    });
</script>
@endsection