routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::group(['middleware' => 'api', 'prefix' => 'api/sale'], function () {

    Route::get('/', [
        'uses' => 'ApiSaleController@index',
        'as' => 'api.sale',
    ]);

    Route::get('/total', [
        'uses' => 'ApiSaleController@total',
        'as' => 'api.sale.total',
    ]);

});

Route::resource('attendance', 'AttendanceController');

Route::get('/', [
    'uses' => 'HomeController@index',
    'as' => 'home',
]);

Route::group(['middleware' => 'auth'], function () {

    Route::get('/products', [
        'uses' => 'HomeController@products',
        'as' => 'products',
    ]);

    Route::get('/categories', [
        'uses' => 'HomeController@categories',
        'as' => 'categories',
    ]);

    Route::post('/order-product', [
        'uses' => 'HomeController@order',
        'as' => 'order.product',
    ]);

    Route::post('/logout', [
        'uses' => 'Auth\LoginController@logout',
        'as' => 'logout',
    ]);

});

Route::group(['middleware' => 'guest'], function () {

    Route::get('/login', [
        'uses' => 'Auth\LoginController@loginForm',
        'as' => 'login',
    ]);

    Route::post('/login', [
        'uses' => 'Auth\LoginController@login',
        'as' => 'login',
    ]);

    Route::get('/register', [
        'uses' => 'Auth\RegisterController@registrationForm',
        'as' => 'register',
    ]);

    Route::post('/register', [
        'uses' => 'Auth\RegisterController@register',
        'as' => 'register',
    ]);

});

Route::group(['middleware' => 'auth', 'prefix' => 'stock', 'middleware' => ['role:Admin']], function () {

    Route::get('/logs', [
        'uses' => 'StockController@logs',
        'as' => 'stock.logs',
    ]);

});

Route::group(['middleware' => 'auth', 'prefix' => 'cart', 'middleware' => ['role:Client']], function () {

    Route::patch('/process-order/{order}', [
        'uses' => 'CartController@processOrder',
        'as' => 'cart.process-order',
    ]);

    Route::patch('/detach-product/{product}', [
        'uses' => 'CartController@detachProduct',
        'as' => 'cart.detach-product',
    ]);

});

Route::group(['middleware' => 'auth', 'prefix' => 'order-client', 'middleware' => ['role:Client']], function () {

    Route::patch('/cancel-order/{order}', [
        'uses' => 'OrderClientController@cancelOrder',
        'as' => 'order-client.cancel-order',
    ]);

});

Route::group(['middleware' => 'auth', 'middleware' => ['role:Client']], function () {

    Route::resource('/order-client', 'OrderClientController');

    Route::resource('/cart', 'CartController');

});

Route::group(['middleware' => 'auth', 'middleware' => ['role:Cashier']], function () {

    Route::resource('/payslip', 'PayslipController');

});

Route::group(['middleware' => 'auth', 'middleware' => ['role:Admin|Cashier']], function () {

    Route::get('/dashboard', [
        'uses' => 'DashboardController@index',
        'as' => 'dashboard',
    ]);

});

Route::group(['middleware' => 'auth', 'middleware' => ['role:Admin']], function () {

    Route::resource('stock', 'StockController');

    Route::resource('product', 'ProductController');

    Route::resource('category', 'CategoryController');

    Route::resource('payroll', 'PayrollController');

    Route::resource('user', 'UserController');

    Route::resource('supplier', 'SupplierController');

});

Route::group(['middleware' => 'auth', 'middleware' => ['role:Admin|Cashier']], function () {

    Route::resource('transaction', 'TransactionController');

    Route::resource('order', 'OrderController');

});

Route::group(['middleware' => 'auth', 'prefix' => 'order', 'middleware' => ['role:Admin|Cashier']], function () {

    Route::patch('/cancel-order/{order}', [
        'uses' => 'OrderController@cancelOrder',
        'as' => 'order.cancel-order',
    ]);

    Route::patch('/payment-order/{order}', [
        'uses' => 'OrderController@paymentOrder',
        'as' => 'order.payment-order',
    ]);

    Route::patch('/detach-product/{product}', [
        'uses' => 'OrderController@detachProduct',
        'as' => 'order.detach-product',
    ]);

});

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    protected $fillable = [
        'category_id',
        'name',
        'price',
        'picture',
        'discount',
        'caliber',
    ];

    public function category()
    {
        return $this->belongsTo('App\Category');
    }

    public function stocks()
    {
        return $this->hasMany('App\Stock');
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Http\Requests\ProductRequest;
use App\Product;
use Image;
use Session;

class ProductController extends Controller
{
    public function index()
    {
        $products = Product::all();
        return view('modules.product.index', compact('products'));
    }

    public function create()
    {
        $categories = Category::all();
        return view('modules.product.create', compact('categories'));
    }

    public function store(ProductRequest $request)
    {
        $data = $request->all();
        if ($request->has('picture')) {
            $picture = $request->file('picture');
            $filename = time() . '.' . $picture->getClientOriginalExtension();
            $data['picture'] = $filename;
            $background = Image::canvas(480, 360);
            $image = Image::make($picture)->resize(480, 360, function ($c) {
                $c->aspectRatio();
                $c->upsize();
            });
            $background->insert($image, 'center');
            $background->save(public_path('images/' . $filename));
        }
        $product = new Product;
        $product->fill($data)->save();
        Session::flash('flash_message', 'Product has been added!');
        return redirect()->route('product.index');
    }

    public function show($id)
    {
        return;
    }

    public function edit($id)
    {
        $product = Product::find($id);
        $categories = Category::all();
        return view('modules.product.edit', compact('product', 'categories'));
    }

    public function update(ProductRequest $request, $id)
    {
        $data = $request->all();
        if ($request->has('picture')) {
            $picture = $request->file('picture');
            $filename = time() . '.' . $picture->getClientOriginalExtension();
            $data['picture'] = $filename;
            $background = Image::canvas(480, 360);
            $image = Image::make($picture)->resize(480, 360, function ($c) {
                $c->aspectRatio();
                $c->upsize();
            });
            $background->insert($image, 'center');
            $background->save(public_path('images/' . $filename));
        }
        $product = Product::find($id);
        $product->update($data);
        Session::flash('flash_message', 'Product has been updated!');
        return redirect()->route('product.index');
    }

    public function destroy($id)
    {
        $product = Product::find($id);
        $product->delete();
        Session::flash('flash_message', 'Product has been deleted!');
        return redirect()->back();
    }
}

resources/views/modules/product/create.blade.php
@extends('layouts.admin')
@section('content')
<div class="row">
    <div class="col-lg-12">
        @include('partials.helper._message')
        <h1>Product <small>Product create</small></h1>
    </div>
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title"><i class="fa fa-shopping-bag"></i> Product create</h3>
            </div>
            <div class="panel-body">
                <form action="{{route('product.store')}}" method="POST" enctype="multipart/form-data">
                    {{ csrf_field() }}
                    <div class="row">
                        <div class="col-sm-3">
                            <center>
                            <a class="thumbnail" href="#" data-target="#picture">
                                <img id="picture_view" src="{{ asset('images/dummy_product.png') }}" height="200" width="200" class="img-responsive" alt="picture">
                            </a>
                            </center>
                            <div class="form-group">
                                <button type="button" class="btn btn-info form-control" id="file-upload">
                                    <i class="fa fa-camera" aria-hidden="true"></i>
                                </button>
                                <input type="file" name="picture" id="picture" class="hide" accept="image/*">
                            </div>
                        </div>
                        <div class="col-sm-9">
                            <div class="form-group">
                                <label>Product</label>
                                <input required name="name" value="{{old('name')}}" class="form-control" placeholder="Product">
                            </div>
                            <div class="form-group">
                                <label>Caliber</label>
                                <input name="caliber" value="{{old('caliber')}}" class="form-control" placeholder="Caliber">
                            </div>
                            <div class="form-group">
                                <label>Category</label>
                                <select required name="category_id" class="form-control">
                                    <option {{ old('category_id') === null ? 'selected' : '' }} disabled>Select Category</option>
                                    @foreach($categories as $category)
                                    <option value="{{$category->id}}" {{ old('category_id') === $category->id ? 'selected' : '' }}>{{$category->name}}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="form-group">
                                <label>Price</label>
                                <input required name="price" value="{{old('price')}}" class="form-control" placeholder="Price">
                            </div>
                            <div class="form-group">
                                <label>Discount(%)</label>
                                <input name="discount" value="{{old('discount')}}" class="form-control" placeholder="Discount">
                            </div>
                            <div class="form-group">
                                <button type="submit" class="btn btn-success form-control">Save</button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection
@section('scripts')
<script>
    function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();
            reader.onload = function (e) {
                $('#picture_view').attr('src', e.target.result);
            }
            reader.readAsDataURL(input.files[0]);
        }
    }
    $("#picture").change(function(){
        readURL(this);
    });
    $("#file-upload").on('click',function(){
       $("#picture").click();
    });
</script>
@endsection

resources/views/modules/product/edit.blade.php
@extends('layouts.admin')
@section('content')
<div class="row">
    <div class="col-lg-12">
        @include('partials.helper._message')
        <h1>Product <small>Product edit</small></h1>
    </div>
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title"><i class="fa fa-shopping-bag"></i> Product edit</h3>
            </div>
            <div class="panel-body">
                <form action="{{route('product.update', $product->id)}}" method="POST" enctype="multipart/form-data">
                    {{ method_field('PATCH') }}
                    {{ csrf_field() }}
                    <div class="row">
                        <div class="col-sm-3">
                            <center>
                            <a class="thumbnail" href="#" data-target="#picture">
                                <img id="picture_view" src="{{ asset('images/'. $product->picture) }}" height="200" width="200" class="img-responsive" alt="picture">
                            </a>
                            </center>
                            <div class="form-group">
                                <button type="button" class="btn btn-info form-control" id="file-upload">
                                <i class="fa fa-camera" aria-hidden="true"></i>
                                </button>
                                <input type="file" name="picture" id="picture" class="hide" accept="image/*">
                            </div>
                        </div>
                        <div class="col-sm-9">
                            <div class="form-group">
                                <label>Product</label>
                                <input required name="name" value="{{$product->name}}" class="form-control" placeholder="Product">
                            </div>
                            <div class="form-group">
                                <label>Caliber</label>
                                <input name="caliber" value="{{$product->caliber}}" class="form-control" placeholder="Caliber">
                            </div>
                            <div class="form-group">
                                <label>Category</label>
                                <select required name="category_id" class="form-control">
                                    <option {{ empty($product->category) ? 'selected' : '' }} disabled>Select Category</option>
                                    @foreach($categories as $category)
                                    <option value="{{$category->id}}" @if(!empty($product->category)) {{ $product->category->id === $category->id ? 'selected' : '' }} @endif>{{$category->name}}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="form-group">
                                <label>Price</label>
                                <input required name="price" value="{{$product->price}}" class="form-control" placeholder="Price">
                            </div>
                            <div class="form-group">
                                <label>Discount(%)</label>
                                <input name="discount" value="{{$product->discount}}" class="form-control" placeholder="Discount">
                            </div>
                            <div class="form-group">
                                <button type="submit" class="btn btn-success form-control">Update</button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection
@section('scripts')
<script>
    function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();
            reader.onload = function (e) {
                $('#picture_view').attr('src', e.target.result);
            }
            reader.readAsDataURL(input.files[0]);
        }
    }
    $("#picture").change(function(){
        readURL(this);
    });
    $("#file-upload").on('click',function(){
        $("#picture").click();
    });
</script>
@endsection

resources/views/modules/product/index.blade.php
@extends('layouts.admin')
@section('content')
<div class="row">
    <div class="col-lg-12">
        @include('partials.helper._message')
        <h1>Product <small>Product list</small></h1>
        <a href="{{route('product.create')}}" class="btn btn-info mgt-b10">Create Product</a>
    </div>
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title"><i class="fa fa-shopping-bag"></i> Product list</h3>
            </div>
            <div class="panel-body">
                <div class="table-responsive">
                    <table class="table table-striped" id="datatable">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Name</th>
                                <th>Caliber</th>
                                <th>Category</th>
                                <th>Price</th>
                                <th>Discount(%)</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($products as $product)
                            <tr>
                                <td>{{$product->id}}</td>
                                <td>{{$product->name}}</td>
                                <td>{{$product->caliber}}</td>
                                <td>{{empty($product->category) ? '' : $product->category->name}}</td>
                                <td>{{$product->price}}</td>
                                <td>{{$product->discount}}</td>
                                <td>
                                    <a href="{{route('product.edit', $product->id)}}" class="btn btn-info"><i class="fa fa-pencil-square-o"></i></a>
                                    <button type="submit" form="product-delete-{{$product->id}}" class="btn btn-danger"><i class="fa fa-trash-o"></i></button>
                                    <form onsubmit="return confirm('Do you want to delete this data?');" id="product-delete-{{$product->id}}" action="{{route('product.destroy', $product->id)}}" method="POST">
                                        {{ method_field('DELETE') }}
                                        {{ csrf_field() }}
                                    </form>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
@section('scripts')
<script>
    $(document).ready(function(){
        $('#datatable').DataTable();
    });
</script>
@endsection